In [ ]:
#L1 Combine ser1 and ser2 to form a dataframe.  

import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))


df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())

In [ ]:

ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz')
                
ser.name = 'alphabets'
ser.head()

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

df = pd.DataFrame(ser.values.reshape(7,5))

In [ ]:
import pandas as pd
# Apply the function, f(x) = x/2 on each and every element of a given pandas series

series = pd.Series([2, 4, 6, 8, 10])

print(series) # pandas series initially

print()

modified_series = series.apply(lambda x:x/2)

In [ ]:
# sort the following df by its id and then by its age
'''
    id  name    age   occupation
0   2   Vinay   22    engineer
1   1  Kushal   25      doctor
2   1    Aman   24  accountant
'''

dataframe_sorted = dataframe.sort_values(by = ['id', 'age'])

In [ ]:
# Find the entries that has an age gretar than 23
dataframe_condition = dataframe.loc[dataframe.age >= 24]

In [ ]:
'''
     name       occ  salary
0   Vinay  engineer   60000
1  Kushal    doctor   70000
2    Aman  engineer   50000
3   Rahul    doctor   60000
4  Ramesh    doctor   65000
'''
# Given is a dataframe showing name, occupation, salary of people. 
# Find the average salary per occupation

occ_average_age = dataframe.groupby('occ')['salary'].mean() # required dataframe

In [ ]:
'''
     name       occ   salary
0   Vinay  engineer      NaN
1  Kushal    doctor  70000.0
2    Aman  engineer      NaN
3   Rahul    doctor  60000.0
4  Ramesh    doctor  65000.0
'''
# fill the NaN values with 0
dataframe_nullfill = dataframe.fillna(0)

In [ ]:
'''
                cname  profit
0         Shyam & Co.  -10000
1      Ramlal & Bros.   10000
2  Sharma Enterprises   -5000
3    Verma Furnitures   15000
4        Rahul Stores   20000

Given is a dataframe showing Company Names (cname) and corresponding Profits (profit). 
Convert the values of Profit column such that values in it greater than 0 
are set to True and the rest are set to False.
'''
company_data['profit'] = company_data['profit'].apply(lambda x:x>0)

In [ ]:
'''
   eid   ename  stipend         position
0    1     Sid    10000         employee
1    2  Ramesh    10000         employee
2    3     Ron     5000           intern
3    4   Harry    15000  senior_employee
'''
#For the table above, generate the statistical summary of all the numerical features
dataframe.describe()

In [15]:
import numpy as np
import math

#Read the csv file using the following code. 

Admission = pd.read_csv("datasets/Admission_Predict.csv", delimiter=",", header=0)
Admission

# List  first 10 rows

# List the GRE Score of all students. 

# list GRE and TOEFL scores of all students 

# Normalize the GRE scores so that they are between 0 and 100 and add this as another column
##### note that this should be another dataframe, don't change the original one. 

# Normalize the CGPA such that the values are between 0 and 4 and add this as another column.
###### again, don't change the original one. 

# In the revised data frame, drop the old (unnormalized) CGPA columns and old (unnormalized) GRE score 
#### columns. 

# List those whose CGPA is higher than 0.50. 

# Find the average of CGPA for those whose chance of admit is higher than 0.50

# Print the average CGPA for those  whose chance of admit is higher than 0.50 and university rating is 
##### 1 or 2. 

# Generate a new column called results. For those whose chance of admit is greater than 0.80, 
##### if their CGPA (normalized) is higher than 3.5 then the results column should be "Pass"
##### and the others should be "Fail".

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45
10,11,325,106,3,3.5,4.0,8.40,1,0.52
11,12,327,111,4,4.0,4.5,9.00,1,0.84
12,13,328,112,4,4.0,4.5,9.10,1,0.78
13,14,307,109,3,4.0,3.0,8.00,1,0.62
14,15,311,104,3,3.5,2.0,8.20,1,0.61
15,16,314,105,3,3.5,2.5,8.30,0,0.54
16,17,317,107,3,4.0,3.0,8.70,0,0.66
17,18,319,106,3,4.0,3.0,8.00,1,0.65
18,19,318,110,3,4.0,3.0,8.80,0,0.63
19,20,303,102,3,3.5,3.0,8.50,0,0.62
20,21,312,107,3,3.0,2.0,7.90,1,0.64
21,22,325,114,4,3.0,2.0,8.40,0,0.70
22,23,328,116,5,5.0,5.0,9.50,1,0.94
23,24,334,119,5,5.0,4.5,9.70,1,0.95
24,25,336,119,5,4.0,3.5,9.80,1,0.97
25,26,340,120,5,4.5,4.5,9.60,1,0.94
26,27,322,109,5,4.5,3.5,8.80,0,0.76
27,28,298,98,2,1.5,2.5,7.50,1,0.44
28,29,295,93,1,2.0,2.0,7.20,0,0.46
29,30,310,99,2,1.5,2.0,7.30,0,0.54
...,...,...,...,...,...,...,...,...,...
370,371,310,103,2,2.5,2.5,8.24,0,0.72
371,372,324,110,3,3.5,3.0,9.22,1,0.89
372,373,336,119,4,4.5,4.0,9.62,1,0.95
373,374,321,109,3,3.0,3.0,8.54,1,0.79
374,375,315,105,2,2.0,2.5,7.65,0,0.39
375,376,304,101,2,2.0,2.5,7.66,0,0.38
376,377,297,96,2,2.5,2.0,7.43,0,0.34
377,378,290,100,1,1.5,2.0,7.56,0,0.47
378,379,303,98,1,2.0,2.5,7.65,0,0.56
379,380,311,99,1,2.5,3.0,8.43,1,0.71
380,381,322,104,3,3.5,4.0,8.84,1,0.78
381,382,319,105,3,3.0,3.5,8.67,1,0.73
382,383,324,110,4,4.5,4.0,9.15,1,0.82
383,384,300,100,3,3.0,3.5,8.26,0,0.62
384,385,340,113,4,5.0,5.0,9.74,1,0.96
385,386,335,117,5,5.0,5.0,9.82,1,0.96
386,387,302,101,2,2.5,3.5,7.96,0,0.46
387,388,307,105,2,2.0,3.5,8.10,0,0.53
388,389,296,97,2,1.5,2.0,7.80,0,0.49
389,390,320,108,3,3.5,4.0,8.44,1,0.76
390,391,314,102,2,2.0,2.5,8.24,0,0.64
391,392,318,106,3,2.0,3.0,8.65,0,0.71
392,393,326,112,4,4.0,3.5,9.12,1,0.84
393,394,317,104,2,3.0,3.0,8.76,0,0.77
394,395,329,111,4,4.5,4.0,9.23,1,0.89
395,396,324,110,3,3.5,3.5,9.04,1,0.82
396,397,325,107,3,3.0,3.5,9.11,1,0.84
397,398,330,116,4,5.0,4.5,9.45,1,0.91
398,399,312,103,3,3.5,4.0,8.78,0,0.67
399,400,333,117,4,5.0,4.0,9.66,1,0.95