# Scales

In [ ]:
# Let's bring in pandas as normal
import pandas as pd

# Here’s an example. Lets create a dataframe of letter grades in descending order. We can also set an index
# value and here we'll just make it some human judgement of how good a student was, like "excellent" or "good"

df=pd.DataFrame(['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D+', 'D'],
                index=['excellent', 'excellent', 'excellent', 'good', 'good', 'good', 
                       'ok', 'ok', 'ok', 'poor', 'poor'],
               columns=["Grades"])
df

In [ ]:
# Now, if we check the datatype of this column, we see that it's just an object, since we set string values
df.dtypes

In [ ]:
# We can, however, tell pandas that we want to change the type to category, using the astype() function
df["Grades"].astype("category")
#df["Grades"].astype("category").head()

In [ ]:
df[df["Grades"]>"B-"] 
#It knows that they are ordered. However the order is not correct.

In [ ]:
# Now correct the orders. 

my_categories=pd.CategoricalDtype(categories=['D', 'D+', 'C-', 'C', 'C+', 'B-', 'B', 'B+', 'A-', 'A', 'A+'], 
                           ordered=True)
# then we can just pass this to the astype() function

In [ ]:
my_categories

In [ ]:
df_corr=df["Grades"].astype(my_categories)

In [ ]:
# So a C+ is great than a C, but a C- and D certainly are not. However, if we broadcast over the dataframe
# which has the type set to an ordered categorical

df_corr[df_corr>"C"]

In [ ]:
df[df["Grades"]>"C"]

In [ ]:
# We see that the operator works as we would expect. We can then use a certain set of mathematical operators,
# like minimum, maximum, etc., on the ordinal data.

In [ ]:
# Sometimes it is useful to represent categorical values as each being a column with a true or a false as to
# whether the category applies. This is especially common in feature extraction, which is a topic in the data
# mining course. Variables with a boolean value are typically called dummy variables, and pandas has a built
# in function called get_dummies which will convert the values of a single column into multiple columns of
# zeros and ones indicating the presence of the dummy variable. I rarely use it, but when I do it's very
# handy.

In [ ]:
# There’s one more common scale-based operation I’d like to talk about, and that’s on converting a scale from
# something that is on the interval or ratio scale, like a numeric grade, into one which is categorical. Now,
# this might seem a bit counter intuitive to you, since you are losing information about the value. But it’s
# commonly done in a couple of places. For instance, if you are visualizing the frequencies of categories,
# this can be an extremely useful approach, and histograms are regularly used with converted interval or ratio
# data. In addition, if you’re using a machine learning classification approach on data, you need to be using
# categorical data, so reducing dimensionality may be useful just to apply a given technique. Pandas has a
# function called cut which takes as an argument some array-like structure like a column of a dataframe or a
# series. It also takes a number of bins to be used, and all bins are kept at equal spacing.
 
# Lets go back to our census data for an example. We saw that we could group by state, then aggregate to get a
# list of the average county size by state. If we further apply cut to this with, say, ten bins, we can see
# the states listed as categoricals using the average county size.

In [32]:
# let's bring in numpy
import numpy as np

# Now we read in our dataset
df=pd.read_csv("datasets/mpg.csv", index_col=0)

pd.cut(df['cty'],2)

1      (8.974, 22.0]
2      (8.974, 22.0]
3      (8.974, 22.0]
4      (8.974, 22.0]
5      (8.974, 22.0]
6      (8.974, 22.0]
7      (8.974, 22.0]
8      (8.974, 22.0]
9      (8.974, 22.0]
10     (8.974, 22.0]
11     (8.974, 22.0]
12     (8.974, 22.0]
13     (8.974, 22.0]
14     (8.974, 22.0]
15     (8.974, 22.0]
16     (8.974, 22.0]
17     (8.974, 22.0]
18     (8.974, 22.0]
19     (8.974, 22.0]
20     (8.974, 22.0]
21     (8.974, 22.0]
22     (8.974, 22.0]
23     (8.974, 22.0]
24     (8.974, 22.0]
25     (8.974, 22.0]
26     (8.974, 22.0]
27     (8.974, 22.0]
28     (8.974, 22.0]
29     (8.974, 22.0]
30     (8.974, 22.0]
           ...
205    (8.974, 22.0]
206    (8.974, 22.0]
207    (8.974, 22.0]
208    (8.974, 22.0]
209    (8.974, 22.0]
210    (8.974, 22.0]
211    (8.974, 22.0]
212    (8.974, 22.0]
213     (22.0, 35.0]
214    (8.974, 22.0]
215    (8.974, 22.0]
216    (8.974, 22.0]
217    (8.974, 22.0]
218    (8.974, 22.0]
219    (8.974, 22.0]
220    (8.974, 22.0]
221    (8.974, 22.0]
222     (22.0, 35.0]
223     (22.0, 35.0]
224    (8.974, 22.0]
225    (8.974, 22.0]
226    (8.974, 22.0]
227    (8.974, 22.0]
228    (8.974, 22.0]
229    (8.974, 22.0]
230    (8.974, 22.0]
231    (8.974, 22.0]
232    (8.974, 22.0]
233    (8.974, 22.0]
234    (8.974, 22.0]
Name: cty, Length: 234, dtype: category
Categories (2, interval[float64]): [(8.974, 22.0] < (22.0, 35.0]]

In [33]:
df

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
6,audi,a4,2.8,1999,6,manual(m5),f,18,26,p,compact
7,audi,a4,3.1,2008,6,auto(av),f,18,27,p,compact
8,audi,a4 quattro,1.8,1999,4,manual(m5),4,18,26,p,compact
9,audi,a4 quattro,1.8,1999,4,auto(l5),4,16,25,p,compact
10,audi,a4 quattro,2.0,2008,4,manual(m6),4,20,28,p,compact
11,audi,a4 quattro,2.0,2008,4,auto(s6),4,19,27,p,compact
12,audi,a4 quattro,2.8,1999,6,auto(l5),4,15,25,p,compact
13,audi,a4 quattro,2.8,1999,6,manual(m5),4,17,25,p,compact
14,audi,a4 quattro,3.1,2008,6,auto(s6),4,17,25,p,compact
15,audi,a4 quattro,3.1,2008,6,manual(m6),4,15,25,p,compact
16,audi,a6 quattro,2.8,1999,6,auto(l5),4,15,24,p,midsize
17,audi,a6 quattro,3.1,2008,6,auto(s6),4,17,25,p,midsize
18,audi,a6 quattro,4.2,2008,8,auto(s6),4,16,23,p,midsize
19,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
20,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,11,15,e,suv
21,chevrolet,c1500 suburban 2wd,5.3,2008,8,auto(l4),r,14,20,r,suv
22,chevrolet,c1500 suburban 2wd,5.7,1999,8,auto(l4),r,13,17,r,suv
23,chevrolet,c1500 suburban 2wd,6.0,2008,8,auto(l4),r,12,17,r,suv
24,chevrolet,corvette,5.7,1999,8,manual(m6),r,16,26,p,2seater
25,chevrolet,corvette,5.7,1999,8,auto(l4),r,15,23,p,2seater
26,chevrolet,corvette,6.2,2008,8,manual(m6),r,16,26,p,2seater
27,chevrolet,corvette,6.2,2008,8,auto(s6),r,15,25,p,2seater
28,chevrolet,corvette,7.0,2008,8,manual(m6),r,15,24,p,2seater
29,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,14,19,r,suv
30,chevrolet,k1500 tahoe 4wd,5.3,2008,8,auto(l4),4,11,14,e,suv
...,...,...,...,...,...,...,...,...,...,...,...
205,toyota,toyota tacoma 4wd,3.4,1999,6,auto(l4),4,15,19,r,pickup
206,toyota,toyota tacoma 4wd,4.0,2008,6,manual(m6),4,15,18,r,pickup
207,toyota,toyota tacoma 4wd,4.0,2008,6,auto(l5),4,16,20,r,pickup
208,volkswagen,gti,2.0,1999,4,manual(m5),f,21,29,r,compact
209,volkswagen,gti,2.0,1999,4,auto(l4),f,19,26,r,compact
210,volkswagen,gti,2.0,2008,4,manual(m6),f,21,29,p,compact
211,volkswagen,gti,2.0,2008,4,auto(s6),f,22,29,p,compact
212,volkswagen,gti,2.8,1999,6,manual(m5),f,17,24,r,compact
213,volkswagen,jetta,1.9,1999,4,manual(m5),f,33,44,d,compact
214,volkswagen,jetta,2.0,1999,4,manual(m5),f,21,29,r,compact
215,volkswagen,jetta,2.0,1999,4,auto(l4),f,19,26,r,compact
216,volkswagen,jetta,2.0,2008,4,auto(s6),f,22,29,p,compact
217,volkswagen,jetta,2.0,2008,4,manual(m6),f,21,29,p,compact
218,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact
219,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact
220,volkswagen,jetta,2.8,1999,6,auto(l4),f,16,23,r,compact
221,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact
222,volkswagen,new beetle,1.9,1999,4,manual(m5),f,35,44,d,subcompact
223,volkswagen,new beetle,1.9,1999,4,auto(l4),f,29,41,d,subcompact
224,volkswagen,new beetle,2.0,1999,4,manual(m5),f,21,29,r,subcompact
225,volkswagen,new beetle,2.0,1999,4,auto(l4),f,19,26,r,subcompact
226,volkswagen,new beetle,2.5,2008,5,manual(m5),f,20,28,r,subcompact
227,volkswagen,new beetle,2.5,2008,5,auto(s6),f,20,29,r,subcompact
228,volkswagen,passat,1.8,1999,4,manual(m5),f,21,29,p,midsize
229,volkswagen,passat,1.8,1999,4,auto(l5),f,18,29,p,midsize
230,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
231,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
232,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
233,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
234,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [39]:
df.pivot_table(values='cty', index='manufacturer', columns='year', aggfunc=[np.mean, np.max,np.min]).head()

                   mean            amax      amin
year               1999       2008 1999 2008 1999 2008
manufacturer
audi          17.111111  18.111111   21   21   15   15
chevrolet     15.142857  14.916667   19   22   11   11
dodge         13.375000  12.952381   18   17   11    9
ford          13.933333  14.100000   18   17   11   12
honda         24.800000  24.000000   28   26   23   21